name: My Python Image CI

on:
  push:
    branches: [develop, main]

jobs:
  build-develop:
    if: github.ref == 'refs/heads/develop'
    uses: .github/workflows/_build-template.yml
    with:
      branch: develop
      push_latest: false
    secrets: inherit

  build-main:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_build-template.yml
    with:
      branch: main
      push_latest: true
    secrets: inherit
